from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="ELMC 3D API",
        default_version='v1',
        description="API pentru platforma ELMC 3D",
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)
urlpatterns = [
    path('', views.Intro, name='intro'),
    path('view-3d/<str:file_id>/', views.view_3d, name='view_3d'),
    path('home/', views.home, name='home'),
    path('api/auth/register/', views.register_user, name='register'),
    path('api/auth/login/', views.login_user, name='login'),
    path('api/proxy/overpass/', views.proxy_overpass, name='proxy_overpass'),
    path('api/auth/logout/', views.logout_user, name='logout'),
    path('api/users/me/', views.get_user_profile, name='profile'),
    path('api/models/import/', views.save_building_data, name='save_building_data'),
    path('api/models/<str:file_id>/', views.model_router, name='api_model'),
    path('api/models/<str:file_id>/export/', views.export_glb, name='export_glb'),
    path('api/files/<str:filename>/', views.download_file, name='download_file'),
    path('api/cache/', views.clear_building_data, name='clear_building_data'),
    path('api/session/', views.get_session_info, name='session_info'),
    path('api/health/', views.health_check, name='health_check'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('api/docs/', views.api_docs, name='api_docs'),
    path('auth/', views.auth_page, name='auth_page'),
    path('api/textures/element/', views.element_texture, name='element_texture'),
    path('api/textures/', views.available_textures, name='available_textures'),
    path('account/', views.account_page, name='account_page'),
    path('api/users/me/profile/', views.update_profile, name='update_profile'),
    path('api/users/me/password/', views.change_password, name='change_password'),
    path('api/users/me/models/', views.get_user_models, name='get_user_models'),
    path('api/users/me/stats/', views.get_account_stats, name='get_account_stats'),
    path('api/models/export/', views.save_export, name='save_export'),
    path('api/users/me/models/detailed/', views.get_user_models_detailed, name='get_user_models_detailed'),
    path('api/models/export/<str:file_id>/', views.download_export, name='download_export'),
    path('api/models/export/<str:file_id>/glb/', views.get_glb_file, name='get_glb_file'),
    path('api/models/<str:file_id>/archive/', views.download_model_archive, name='download_model_archive'),
    path('api/models/<str:file_id>/thumbnail/', views.update_project_thumbnail, name='update_project_thumbnail'),
    path('api/models/<str:file_id>/thumbnail/image/', views.get_project_thumbnail, name='get_project_thumbnail'),
    path('api/models/<str:file_id>/camera/', views.get_project_camera_position, name='get_project_camera_position'),
    path('api/models/<str:file_id>/update/', views.update_model, name='update_model'),
    path('api/models/<str:file_id>/delete/', views.delete_model, name='delete_model'),
    path('api/models/<str:file_id>/stats/', views.get_model_stats, name='get_model_stats'),
    path('api/models/<str:file_id>/visibility/', views.toggle_model_visibility, name='toggle_model_visibility'),
    path('workshop/', views.workshop_page, name='workshop_page'),
    path('api/models/', views.get_public_models, name='get_public_models'),
    path('api/models/<str:file_id>/views/', views.increment_model_view, name='increment_model_view'),
    path('api/models/<str:file_id>/favorites/', views.toggle_favorite, name='toggle_favorite'),
    path('api/users/me/favorites/', views.get_user_favorites, name='get_user_favorites'),
    path('api/workshop-stats/', views.get_workshop_stats, name='workshop_stats'),
    path('api/models/featured/', views.get_featured_models, name='featured_models'),
    path('api/users/me/', views.delete_account, name='delete_account'),
    path('sw.js', views.service_worker_root, name='service_worker_root'),
    path('manifest.json', views.manifest_json, name='manifest_json'),
    path('offline/', views.offline_view, name='offline'),

    
    path('api-docs/pages/intro/', views.doc_intro),
    path('api-docs/pages/home/', views.doc_home),
    path('api-docs/pages/auth/', views.doc_auth),
    path('api-docs/pages/account/', views.doc_account),
    path('api-docs/pages/workshop/', views.doc_workshop),
    path('api-docs/pages/view-3d/<str:file_id>/', views.doc_view_3d),
    path('api-docs/pages/offline/', views.doc_offline),
    path('api-docs/auth/register/', views.doc_register),
    path('api-docs/auth/login/', views.doc_login),
    path('api-docs/auth/logout/', views.doc_logout),
    path('api-docs/auth/profile/', views.doc_get_profile),
    path('api-docs/users/me/', views.doc_get_profile),
    path('api-docs/users/me/profile/', views.doc_update_profile),
    path('api-docs/users/me/password/', views.doc_change_password),
    path('api-docs/users/me/stats/', views.doc_account_stats),
    path('api-docs/users/me/models/', views.doc_user_models_detailed),
    path('api-docs/users/me/favorites/', views.doc_user_favorites),
    path('api-docs/users/me/', views.doc_delete_account),
    path('api-docs/models/import/', views.doc_save_data),
    path('api-docs/models/export/', views.doc_save_export),
    path('api-docs/models/<str:file_id>/', views.doc_update_model),
    path('api-docs/models/<str:file_id>/visibility/', views.doc_toggle_visibility),
    path('api-docs/models/<str:file_id>/data/', views.doc_get_building_data),
    path('api-docs/models/<str:file_id>/data/download/', views.doc_download_building_data),
    path('api-docs/models/<str:file_id>/export/', views.doc_export_glb),
    path('api-docs/models/<str:file_id>/archive/', views.doc_download_model_archive),
    path('api-docs/models/<str:file_id>/thumbnail/', views.doc_update_project_thumbnail),
    path('api-docs/models/<str:file_id>/thumbnail/image/', views.doc_get_project_thumbnail),
    path('api-docs/models/<str:file_id>/camera/', views.doc_get_camera_position),
    path('api-docs/workshop/public-models/', views.doc_public_models),
    path('api-docs/workshop/favorite/<str:file_id>/', views.doc_toggle_favorite),
    path('api-docs/workshop/stats/', views.doc_workshop_stats),
    path('api-docs/workshop/featured/', views.doc_featured_models),
    path('api-docs/workshop/views/<str:file_id>/', views.doc_increment_model_view),
    path('api-docs/files/download/<str:filename>/', views.doc_download_file),
    path('api-docs/files/glb/<str:file_id>/', views.doc_get_glb_file),
    path('api-docs/files/download-export/<str:file_id>/', views.doc_download_export),
    path('api-docs/files/archive/<str:file_id>/', views.doc_download_model_archive),
    path('api-docs/textures/', views.doc_available_textures),
    path('api-docs/textures/element/', views.doc_element_texture),
    path('api-docs/health/', views.doc_health),
    path('api-docs/session/', views.doc_session_info),
    path('api-docs/cache/', views.doc_clear_data),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)